// no-extra-semi and no-mixed-spaces-and-tabs missing

// just gonna hard-code these. Easier to reason about than extending the opaque ruleset
// from https://github.com/eslint/eslint/blob/17f2aaec16d5afbb0d219bce6ae01d7b15d74828/packages/js/src/configs/eslint-recommended.js
const eslintRecommendedRules = {
   'constructor-super': 'error',
   'for-direction': 'error',
   'getter-return': 'error',
   'no-async-promise-executor': 'error',
   'no-case-declarations': 'error',
   'no-class-assign': 'error',
   'no-compare-neg-zero': 'error',
   'no-cond-assign': 'error',
   'no-const-assign': 'error',
   'no-constant-binary-expression': 'error',
   'no-constant-condition': 'error',
   'no-control-regex': 'error',
   'no-debugger': 'error',
   'no-delete-var': 'error',
   'no-dupe-args': 'error',
   'no-dupe-class-members': 'error',
   'no-dupe-else-if': 'error',
   'no-dupe-keys': 'error',
   'no-duplicate-case': 'error',
   'no-empty': 'error',
   'no-empty-character-class': 'error',
   'no-empty-pattern': 'error',
   'no-empty-static-block': 'error',
   'no-ex-assign': 'error',
   'no-extra-boolean-cast': 'error',
   'no-fallthrough': 'error',
   'no-func-assign': 'error',
   'no-global-assign': 'error',
   'no-import-assign': 'error',
   'no-invalid-regexp': 'error',
   'no-irregular-whitespace': 'error',
   'no-loss-of-precision': 'error',
   'no-misleading-character-class': 'error',
   'no-new-native-nonconstructor': 'error',
   'no-nonoctal-decimal-escape': 'error',
   'no-obj-calls': 'error',
   'no-octal': 'error',
   'no-prototype-builtins': 'error',
   'no-redeclare': 'error',
   'no-regex-spaces': 'error',
   'no-self-assign': 'error',
   'no-setter-return': 'error',
   'no-shadow-restricted-names': 'error',
   'no-sparse-arrays': 'error',
   'no-this-before-super': 'error',
   'no-undef': 'error',
   'no-unexpected-multiline': 'error',
   'no-unreachable': 'error',
   'no-unsafe-finally': 'error',
   'no-unsafe-negation': 'error',
   'no-unsafe-optional-chaining': 'error',
   'no-unused-labels': 'error',
   'no-unused-private-class-members': 'error',
   'no-unused-vars': 'error',
   'no-useless-backreference': 'error',
   'no-useless-catch': 'error',
   'no-useless-escape': 'error',
   'no-with': 'error',
   'require-yield': 'error',
   'use-isnan': 'error',
   'valid-typeof': 'error'
};

const baseJsRules = {
   'no-console': 'error',
   'curly': ['error', 'all'],
   'dot-location': ['error', 'property'],
   'dot-notation': 'error',
   'eqeqeq': ['error', 'always'],
   'indent': ['error', 3, {
      'SwitchCase': 1
   }],
   'quotes': ['error', 'single', {
      avoidEscape: true
   }],
   'semi': ['error', 'always'],
   'strict': ['error', 'function'],
   'array-callback-return': 'error',
   'block-scoped-var': 'error',
   'consistent-return': 'error',
   'no-alert': 'error',
   'no-else-return': 'error',
   'no-empty-function': 'error',
   'no-eval': 'error',
   'no-extend-native': 'error',
   'no-implicit-globals': 'error',
   'no-implied-eval': 'error',
   'no-iterator': 'error',
   'no-labels': 'error',
   'no-lone-blocks': 'error',
   'no-loop-func': 'error',
   'no-magic-numbers': ['error', {
      ignoreArrayIndexes: true,
      ignore: [-1, 0, 1, 2, 10, 60, 100, 1000]
   }],
   'no-multi-spaces': 'error',
   'no-multi-str': 'error',
   'no-new-func': 'error',
   'no-new-wrappers': 'error',
   'no-new': 'error',
   'no-octal-escape': 'error',
   'no-proto': 'error',
   'no-return-assign': 'error',
   'no-sequences': 'error',
   'no-throw-literal': 'error',
   'no-unmodified-loop-condition': 'error',
   'no-unused-expressions': ['error', {
      allowShortCircuit: true,
      allowTernary: true
   }],
   'no-useless-call': 'error',
   'no-useless-concat': 'error',
   'no-useless-return': 'error',
   'no-void': ['error', {allowAsStatement: true}],
   'radix': 'error',
   'vars-on-top': 'error',
   'wrap-iife': ['error', 'any'],
   'no-shadow': 'error',
   'no-undef-init': 'error',
   'no-undefined': 'error',
   'no-use-before-define': 'error',
   'array-bracket-spacing': ['error', 'never'],
   'brace-style': 'error',
   'camelcase': 'error',
   'comma-dangle': 'error',
   'comma-spacing': 'error',
   'comma-style': 'error',
   'computed-property-spacing': 'error',
   'func-call-spacing': 'error',
   'func-names': ['error', 'never'],
   'func-style': 'error',
   'key-spacing': 'error',
   'keyword-spacing': 'error',
   'max-statements-per-line': 'error',
   'new-cap': 'error',
   'new-parens': 'error',
   'no-array-constructor': 'error',
   'no-bitwise': 'error',
   'no-lonely-if': 'error',
   "no-mixed-operators": [
      "error",
      {
         "groups": [
            ["&", "|", "^", "~", "<<", ">>", ">>>"],
            ["==", "!=", "===", "!==", ">", ">=", "<", "<="],
            ["&&", "||"],
            ["in", "instanceof"]
         ],
         "allowSamePrecedence": true
      }
   ],
   'no-multi-assign': 'error',
   'no-multiple-empty-lines': 'error',
   'no-nested-ternary': 'error',
   'no-new-object': 'error',
   'no-tabs': 'error',
   'no-trailing-spaces': ['error', {skipBlankLines: false}],
   'no-unneeded-ternary': 'error',
   'no-whitespace-before-property': 'error',
   'object-curly-spacing': 'error',
   'object-curly-newline': 'error',
   'object-property-newline': ['error', {allowAllPropertiesOnSameLine: true}],
   'function-call-argument-newline': ['error', 'consistent'],
   'one-var': ['error', 'never'],
   'padded-blocks': ['error', {
      blocks: 'never',
      classes: 'never',
      switches: 'never'
   }],
   'quote-props': ['error', 'as-needed'],
   'semi-spacing': 'error',
   'space-before-blocks': 'error',
   'space-before-function-paren': ['error', {
      'anonymous': 'never',
      'asyncArrow': 'always',
      'named': 'never'
   }],
   'space-in-parens': 'error',
   'space-infix-ops': 'error',
   'space-unary-ops': 'error',
   'unicode-bom': 'error',
   'no-invalid-this': 'error',
   'no-caller': 'error',
   'id-match': 'error',
   'id-denylist': [
      'error',
      'any',
      'Number',
      'number',
      'String',
      'string',
      'Boolean',
      'boolean',
      'Undefined',
      'undefined'
   ],
   'guard-for-in': 'error',
   'spaced-comment': [
      'error',
      'always',
      {
         'markers': [
            '/'
         ]
      }
   ],
   'no-multiple-empty-lines': ['error', {max: 1, maxEOF: 0, maxBOF: 0}]
};

// probably no good reason to keep these separate anymore, but for historical reasons I guess I will.
const es6Rules = {
   'arrow-parens': ['error', 'as-needed'],
   'arrow-spacing': 'error',
   'generator-star-spacing': 'error',
   'no-duplicate-imports': 'error',
   'no-useless-computed-key': 'error',
   'no-useless-constructor': 'error',
   'no-useless-rename': 'error',
   'no-var': 'error',
   'object-shorthand': ['error', 'consistent-as-needed'],
   'prefer-arrow-callback': 'error',
   'prefer-const': 'error',
   'prefer-rest-params': 'error',
   'prefer-spread': 'error',
   'prefer-template': 'error',
   'rest-spread-spacing': 'error',
   'template-curly-spacing': 'error',
   'yield-star-spacing': 'error',
   'jsx-quotes': 'error',
   'prefer-arrow/prefer-arrow-functions': 'error',
   'max-classes-per-file': [
      'error',
      1
   ],
   'arrow-body-style': [
      'error',
      'as-needed'
   ]
}

module.exports = {...eslintRecommendedRules, ...baseJsRules, ...es6Rules};